### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bendly** [loql/niser#20]
#### Events
- [ ] Create a new event (relationship with user, group)
- [ ] Show event list
- [ ] Update an event
- [ ] Delete an event

#### Group
- [ ] Create a group
- [ ] Search groups
- [ ] Invite people into a group
- [ ] Group privilege
- [ ]
